package services

import (
	"testing"
	mocks "testing-demo/mocks/services"
)

//Using the mocks generated by mockery

func Test_MessageProcessor_Sends_Message(t *testing.T) {
	// Arrange
	mockMessageService := &mocks.MessageService{}

	//configure the mock
	mockMessageService.On("Send", "Hello World").Return(true)
	mp := NewMessageProcessor(mockMessageService)

	// Act
	result := mp.Process("Hello World")

	// Assert
	mockMessageService.AssertExpectations(t)
	if result != true {
		t.Errorf("Expected true but got %v", result)
	}
}
